name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
    - name: xcode-build-github-action
      uses: akiojin/xcode-build-github-action@v1.0
      with:
        export-method: development # optional, default is development
        output-directory: .
        team-id: PG2KAM3LR7
        
        
